// Generated by Apple Swift version 5.3.2 effective-4.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef RWRIDER_SWIFT_H
#define RWRIDER_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import FirebaseMessaging;
@import Foundation;
@import GoogleMaps;
@import ObjectiveC;
@import Pulley;
@import UIKit;
@import UserNotifications;
@import WebKit;
#endif

#import <RWRider/RWRider.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="RWRider",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


/// Inherits NSObject to be used in DSFlowController
SWIFT_CLASS("_TtC7RWRider12AppContainer")
@interface AppContainer : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7RWRider14AppCoordinator")
@interface AppCoordinator : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)setup;
@end



@interface AppCoordinator (SWIFT_EXTENSION(RWRider)) <FakeLaunchProtocol>
- (void)didFinishLaunching;
@end



@class UIWindow;
@class UIApplication;
@class UILocalNotification;
@class NSUserActivity;
@protocol UIUserActivityRestoring;
@class UIApplicationShortcutItem;

SWIFT_CLASS("_TtC7RWRider11AppDelegate")
@interface AppDelegate : UIResponder <UIApplicationDelegate>
@property (nonatomic, strong) UIWindow * _Nullable window;
- (void)registerForNotifications;
- (BOOL)application:(UIApplication * _Nonnull)application didFinishLaunchingWithOptions:(NSDictionary<UIApplicationLaunchOptionsKey, id> * _Nullable)launchOptions SWIFT_WARN_UNUSED_RESULT;
- (void)applicationWillResignActive:(UIApplication * _Nonnull)application;
- (void)applicationDidEnterBackground:(UIApplication * _Nonnull)application;
- (void)applicationWillEnterForeground:(UIApplication * _Nonnull)application;
- (void)applicationDidBecomeActive:(UIApplication * _Nonnull)application;
- (void)applicationWillTerminate:(UIApplication * _Nonnull)application;
- (void)application:(UIApplication * _Nonnull)application didReceiveLocalNotification:(UILocalNotification * _Nonnull)notification;
- (void)application:(UIApplication * _Nonnull)application didReceiveRemoteNotification:(NSDictionary * _Nonnull)userInfo;
- (void)application:(UIApplication * _Nonnull)application didFailToRegisterForRemoteNotificationsWithError:(NSError * _Nonnull)error;
- (void)application:(UIApplication * _Nonnull)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData * _Nonnull)deviceToken;
- (BOOL)application:(UIApplication * _Nonnull)app openURL:(NSURL * _Nonnull)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> * _Nonnull)options SWIFT_WARN_UNUSED_RESULT;
- (BOOL)application:(UIApplication * _Nonnull)application continueUserActivity:(NSUserActivity * _Nonnull)userActivity restorationHandler:(void (^ _Nonnull)(NSArray<id <UIUserActivityRestoring>> * _Nullable))restorationHandler SWIFT_WARN_UNUSED_RESULT;
- (void)application:(UIApplication * _Nonnull)application performActionForShortcutItem:(UIApplicationShortcutItem * _Nonnull)shortcutItem completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UNUserNotificationCenter;
@class UNNotification;

@interface AppDelegate (SWIFT_EXTENSION(RWRider)) <UNUserNotificationCenterDelegate>
- (void)userNotificationCenter:(UNUserNotificationCenter * _Nonnull)center willPresentNotification:(UNNotification * _Nonnull)notification withCompletionHandler:(void (^ _Nonnull)(UNNotificationPresentationOptions))completionHandler SWIFT_AVAILABILITY(ios,introduced=10.0);
@end

@class FIRMessaging;
@class FIRMessagingRemoteMessage;

@interface AppDelegate (SWIFT_EXTENSION(RWRider)) <FIRMessagingDelegate>
- (void)messaging:(FIRMessaging * _Nonnull)messaging didReceiveRegistrationToken:(NSString * _Nonnull)fcmToken;
- (void)messaging:(FIRMessaging * _Nonnull)messaging didReceiveMessage:(FIRMessagingRemoteMessage * _Nonnull)remoteMessage;
@end



@class NSCoder;
@class NSBundle;

SWIFT_CLASS("_TtC7RWRider26CampaignListViewController")
@interface CampaignListViewController : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class UITableView;

@interface CampaignListViewController (SWIFT_EXTENSION(RWRider)) <UITableViewDelegate>
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class UITableViewCell;
@class UIView;

@interface CampaignListViewController (SWIFT_EXTENSION(RWRider)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC7RWRider27DACampaignMapViewController")
@interface DACampaignMapViewController : UIViewController
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class PulleyViewController;

@interface DACampaignMapViewController (SWIFT_EXTENSION(RWRider)) <PulleyPrimaryContentControllerDelegate>
- (void)drawerChangedDistanceFromBottomWithDrawer:(PulleyViewController * _Nonnull)drawer distance:(CGFloat)distance bottomSafeArea:(CGFloat)bottomSafeArea;
- (void)drawerPositionDidChangeWithDrawer:(PulleyViewController * _Nonnull)drawer bottomSafeArea:(CGFloat)bottomSafeArea;
@end


@class RACampaignDetail;

SWIFT_CLASS("_TtC7RWRider22DADetailViewController")
@interface DADetailViewController : UIViewController
- (nonnull instancetype)initWithDetail:(RACampaignDetail * _Nonnull)detail;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITextView;

@interface DADetailViewController (SWIFT_EXTENSION(RWRider)) <UITextViewDelegate>
- (void)textViewDidChangeSelection:(UITextView * _Nonnull)textView;
@end

@class PulleyPosition;

@interface DADetailViewController (SWIFT_EXTENSION(RWRider)) <PulleyDrawerViewControllerDelegate>
- (void)drawerPositionDidChangeWithDrawer:(PulleyViewController * _Nonnull)drawer bottomSafeArea:(CGFloat)bottomSafeArea;
- (NSArray<PulleyPosition *> * _Nonnull)supportedDrawerPositions SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_CLASS("_TtC7RWRider13DCHistoryCell")
@interface DCHistoryCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class ConfigRegistration;
@class DSDriver;
@class DSCar;
@class DSLicenseViewModel;
@class DSCarInsuranceViewModel;
@class DSDriverPhotoViewModel;
@class DSChauffeurViewModel;
@class DSInspectionStickerViewModel;
@class DSCarInfoViewModel;
@class DSCarLicensePlateViewModel;
@class DSCarIsAddedViewModel;
@class DSCarPhotoViewModel;
@class RACity;
@class RACityDetail;

SWIFT_CLASS("_TtC7RWRider16DSFlowController")
@interface DSFlowController : NSObject
@property (nonatomic, strong) ConfigRegistration * _Nullable regConfig;
@property (nonatomic, strong) DSDriver * _Nonnull driver;
@property (nonatomic, strong) DSCar * _Nonnull car;
@property (nonatomic, strong) DSLicenseViewModel * _Null_unspecified licenseViewModel;
@property (nonatomic, strong) DSCarInsuranceViewModel * _Null_unspecified insuranceViewModel;
@property (nonatomic, strong) DSDriverPhotoViewModel * _Null_unspecified driverPhotoViewModel;
@property (nonatomic, strong) DSChauffeurViewModel * _Null_unspecified chauffeurViewModel;
@property (nonatomic, strong) DSInspectionStickerViewModel * _Null_unspecified inspectionStickerViewModel;
@property (nonatomic, strong) DSCarInfoViewModel * _Null_unspecified carInfoViewModel;
@property (nonatomic, strong) DSCarLicensePlateViewModel * _Null_unspecified carLicensePlateViewModel;
@property (nonatomic, strong) DSCarIsAddedViewModel * _Null_unspecified carIsAddedViewModel;
@property (nonatomic, strong) DSCarPhotoViewModel * _Null_unspecified frontPhotoViewModel;
@property (nonatomic, strong) DSCarPhotoViewModel * _Null_unspecified backPhotoViewModel;
@property (nonatomic, strong) DSCarPhotoViewModel * _Null_unspecified insidePhotoViewModel;
@property (nonatomic, strong) DSCarPhotoViewModel * _Null_unspecified trunkPhotoViewModel;
- (void)endDriverSignup;
- (void)updateWithCity:(RACity * _Nonnull)city detail:(RACityDetail * _Nonnull)detail;
- (void)submitRegistrationWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


@interface DSFlowController (SWIFT_EXTENSION(RWRider))
- (void)showNextScreenFromScreen:(DSScreen)fromScreen;
- (UIViewController * _Nullable)viewControllerNextToFromScreen:(DSScreen)fromScreen SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP7RWRider31FingerprintsCoordinatorDelegate_")
@protocol FingerprintsCoordinatorDelegate
- (void)didTapNotNow;
- (void)didFinishSuccessfully;
@end


@interface DSFlowController (SWIFT_EXTENSION(RWRider)) <FingerprintsCoordinatorDelegate>
- (void)didTapNotNow;
- (void)didFinishSuccessfully;
@end

@class RADesignatedPickup;

SWIFT_CLASS("_TtC7RWRider15DesignatedPoint")
@interface DesignatedPoint : NSObject
@property (nonatomic, copy) NSString * _Nonnull address;
@property (nonatomic, strong) RADesignatedPickup * _Nonnull point;
- (nonnull instancetype)initWithAddress:(NSString * _Nonnull)address point:(RADesignatedPickup * _Nonnull)point OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC7RWRider27DirectConnectViewController")
@interface DirectConnectViewController : BaseViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface DirectConnectViewController (SWIFT_EXTENSION(RWRider)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class RADriverTypeDataModel;

SWIFT_CLASS("_TtC7RWRider37FingerprintedDriverModeViewController")
@interface FingerprintedDriverModeViewController : BaseViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithModel:(RADriverTypeDataModel * _Nonnull)model OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC7RWRider23FingerprintsCoordinator")
@interface FingerprintsCoordinator : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




SWIFT_CLASS("_TtC7RWRider26FingerprintsViewController")
@interface FingerprintsViewController : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface FingerprintsViewController (SWIFT_EXTENSION(RWRider)) <RAHelpBarViewDelegate>
- (void)didTapHelpBar;
@end


@interface FingerprintsViewController (SWIFT_EXTENSION(RWRider))
- (IBAction)submitButtonTapped:(id _Nonnull)sender;
@end


@class ConfigGlobal;
@class GMSPath;
@class GMSMarker;
@class CLLocation;

SWIFT_CLASS("_TtC7RWRider12HintsService")
@interface HintsService : NSObject
- (nonnull instancetype)initWithGlobal:(ConfigGlobal * _Nonnull)global OBJC_DESIGNATED_INITIALIZER;
- (NSArray<GMSPath *> * _Nonnull)pickupHintAreas SWIFT_WARN_UNUSED_RESULT;
- (NSArray<GMSMarker *> * _Nonnull)designatedPickupPointPinsWithIsPickup:(BOOL)isPickup SWIFT_WARN_UNUSED_RESULT;
- (DesignatedPoint * _Nullable)getNearestPickupPointWithLocation:(CLLocation * _Nonnull)location SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class UIButton;

SWIFT_CLASS("_TtC7RWRider27LocationAlertViewController")
@interface LocationAlertViewController : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (IBAction)allowButtonPressed:(UIButton * _Nonnull)sender;
- (IBAction)notNowButtonPressed:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class RARideLocationDataModel;

SWIFT_CLASS("_TtC7RWRider28LocationPickerViewController")
@interface LocationPickerViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithFieldType:(RAPickerAddressFieldType)fieldType completion:(void (^ _Nonnull)(RAPickerAddressFieldType, RARideLocationDataModel * _Nullable, BOOL))completion OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class GMSMapView;
@class GMSOverlay;
@class GMSCameraPosition;

@interface LocationPickerViewController (SWIFT_EXTENSION(RWRider)) <GMSMapViewDelegate>
- (void)mapView:(GMSMapView * _Nonnull)mapView didTapOverlay:(GMSOverlay * _Nonnull)overlay;
- (void)mapView:(GMSMapView * _Nonnull)mapView idleAtCameraPosition:(GMSCameraPosition * _Nonnull)position;
- (void)mapView:(GMSMapView * _Nonnull)mapView didChangeCameraPosition:(GMSCameraPosition * _Nonnull)position;
@end


SWIFT_CLASS("_TtC7RWRider21PaymentViewController")
@interface PaymentViewController : BaseViewController
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
@end


@interface PaymentViewController (SWIFT_EXTENSION(RWRider)) <UITableViewDelegate>
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


@interface PaymentViewController (SWIFT_EXTENSION(RWRider)) <UITableViewDataSource>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

@class WKWebView;

SWIFT_CLASS("_TtC7RWRider37RiderTermsAndConditionsViewController")
@interface RiderTermsAndConditionsViewController : BaseRegistrationViewController
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified buttonCheckbox;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified buttonAccept;
@property (nonatomic, weak) IBOutlet WKWebView * _Null_unspecified webView;
- (void)viewDidLoad;
- (IBAction)buttonCheckboxTapped:(UIButton * _Nonnull)sender;
- (IBAction)buttonAcceptTapped:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class WKNavigation;

@interface RiderTermsAndConditionsViewController (SWIFT_EXTENSION(RWRider)) <WKNavigationDelegate>
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didFailProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
@end


SWIFT_CLASS("_TtC7RWRider20ShadowBackgroundView")
@interface ShadowBackgroundView : UIView
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7RWRider19SideMenuCoordinator")
@interface SideMenuCoordinator : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class DCDriverDetailViewController;

@interface SideMenuCoordinator (SWIFT_EXTENSION(RWRider)) <DCDriverDetailViewControllerDelegate>
- (BOOL)dcDriverDetailViewControllerCheckLocationPermissions:(DCDriverDetailViewController * _Nullable)dcDriverDetailViewController SWIFT_WARN_UNUSED_RESULT;
@end




@interface SideMenuCoordinator (SWIFT_EXTENSION(RWRider)) <SideMenuProtocol>
- (void)showSideMenu;
- (void)hideSideMenu;
@end


@interface SideMenuCoordinator (SWIFT_EXTENSION(RWRider)) <FingerprintsCoordinatorDelegate>
- (void)didTapNotNow;
- (void)didFinishSuccessfully;
@end

@class VKSideMenu;

@interface SideMenuCoordinator (SWIFT_EXTENSION(RWRider)) <VKSideMenuDelegate>
- (void)sideMenuDidHide:(VKSideMenu * _Nonnull)sideMenu;
- (void)sideMenuDidShow:(VKSideMenu * _Nonnull)sideMenu;
- (void)sideMenu:(VKSideMenu * _Nonnull)sideMenu didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class VKSideMenuItem;

@interface SideMenuCoordinator (SWIFT_EXTENSION(RWRider)) <VKSideMenuDataSource>
- (NSInteger)numberOfSectionsInSideMenu:(VKSideMenu * _Nonnull)sideMenu SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)sideMenu:(VKSideMenu * _Nonnull)sideMenu numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (VKSideMenuItem * _Nonnull)sideMenu:(VKSideMenu * _Nonnull)sideMenu itemForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)sideMenu:(VKSideMenu * _Nonnull)sideMenu headerViewForSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end












#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
